// src/app/opengraph-image.tsx
//
// Open Graph image generated by Next.js' file-based convention.
// Output: GET /opengraph-image -> image/png, 1200x630.
//
// Colours come from src/lib/og-tokens.ts, the documented sRGB mirror of the
// .dark token block in globals.css. Dark theme deliberately: link previews
// mostly render in feeds where the dark card reads as the site's identity,
// and the dark accent #3B82F6 carries both the tile and the glow.

import { ImageResponse } from "next/og";

import {
  OG_GROUND,
  OG_TEXT,
  OG_TEXT_MUTED,
  OG_ACCENT,
  OG_ON_ACCENT,
  OG_ACCENT_RGB,
} from "@/lib/og-tokens";

export const runtime = "edge";

export const alt = "Murat Zorlu: I build the internal tools companies run on";

export const size = {
  width: 1200,
  height: 630,
} as const;

export const contentType = "image/png";

// Satori does not support WOFF2 — it only parses TTF / OTF. Google Fonts
// serves WOFF2 to modern UAs, so these are the static-TTF URLs css2 returns
// to a legacy UA (curl -A "Mozilla/5.0 (Linux; U; Android 4.0)"). gstatic
// asset URLs are immutable, so they are safe to pin.
//
// Same faces the site loads in layout.tsx: Darker Grotesque 800 is the
// display face (headings), Instrument Sans is the body face and the face
// the header's MZ tile and wordmark render in.
const DARKER_GROTESQUE_800_TTF_URL =
  "https://fonts.gstatic.com/s/darkergrotesque/v10/U9MK6cuh-mLQlC4BKCtayOfARkSVgb381b-W8-QDqXy3rX7y.ttf";
const INSTRUMENT_SANS_400_TTF_URL =
  "https://fonts.gstatic.com/s/instrumentsans/v4/pximypc9vsFDm051Uf6KVwgkfoSxQ0GsQv8ToedPibnr-yp2JGEJOH9npSTF-Qf1.ttf";
const INSTRUMENT_SANS_700_TTF_URL =
  "https://fonts.gstatic.com/s/instrumentsans/v4/pximypc9vsFDm051Uf6KVwgkfoSxQ0GsQv8ToedPibnr-yp2JGEJOH9npSQi_gf1.ttf";

async function loadFont(url: string): Promise<ArrayBuffer> {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Failed to download font from ${url}: ${res.status}`);
  }
  return await res.arrayBuffer();
}

export default async function OpengraphImage(): Promise<ImageResponse> {
  const [darkerGrotesque, instrumentSans, instrumentSansBold] =
    await Promise.all([
      loadFont(DARKER_GROTESQUE_800_TTF_URL),
      loadFont(INSTRUMENT_SANS_400_TTF_URL),
      loadFont(INSTRUMENT_SANS_700_TTF_URL),
    ]);

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          background: OG_GROUND,
          color: OG_TEXT,
          fontFamily: "Instrument Sans",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          padding: "72px 80px",
          position: "relative",
        }}
      >
        {/* Top-right radial glow in the accent, same device as the hero. */}
        <div
          style={{
            position: "absolute",
            top: 0,
            right: 0,
            width: "780px",
            height: "780px",
            display: "flex",
            backgroundImage: `radial-gradient(circle at 70% 25%, rgba(${OG_ACCENT_RGB}, 0.20) 0%, rgba(${OG_ACCENT_RGB}, 0.06) 35%, rgba(${OG_ACCENT_RGB}, 0) 70%)`,
          }}
        />

        {/* Header lockup: the MZ tile plus wordmark, dark-theme identity.
            Tile geometry scales the header's 28px rounded-md tile: 64px box,
            64 * (6/28) = 14px radius, 64 * (12/28) = 27px letters. */}
        <div
          style={{
            display: "flex",
            flexDirection: "row",
            alignItems: "center",
            gap: "22px",
            position: "relative",
          }}
        >
          <div
            style={{
              width: "64px",
              height: "64px",
              borderRadius: "14px",
              background: OG_ACCENT,
              color: OG_ON_ACCENT,
              fontSize: 27,
              fontWeight: 700,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            MZ
          </div>
          <div
            style={{
              fontSize: 34,
              fontWeight: 700,
              letterSpacing: "-0.01em",
              display: "flex",
            }}
          >
            Murat Zorlu
          </div>
        </div>

        {/* Headline in the display face. The break is forced: letting it
            wrap at this size strands "on" alone on a third line. */}
        <div
          style={{
            fontFamily: "Darker Grotesque",
            fontSize: 100,
            fontWeight: 800,
            lineHeight: 1.0,
            letterSpacing: "0.002em",
            color: OG_TEXT,
            display: "flex",
            flexDirection: "column",
            position: "relative",
          }}
        >
          <div style={{ display: "flex" }}>I build the internal tools</div>
          <div style={{ display: "flex" }}>companies run on</div>
        </div>

        {/* Bottom row: stack left, domain right. */}
        <div
          style={{
            display: "flex",
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            position: "relative",
          }}
        >
          <div
            style={{
              fontSize: 28,
              color: OG_TEXT_MUTED,
              letterSpacing: "0.02em",
              display: "flex",
            }}
          >
            Next.js · NestJS · Go · PostgreSQL
          </div>
          <div
            style={{
              fontSize: 24,
              color: OG_TEXT_MUTED,
              letterSpacing: "0.06em",
              display: "flex",
            }}
          >
            muratzorlu.dev
          </div>
        </div>
      </div>
    ),
    {
      ...size,
      fonts: [
        {
          name: "Darker Grotesque",
          data: darkerGrotesque,
          weight: 800,
          style: "normal",
        },
        {
          name: "Instrument Sans",
          data: instrumentSans,
          weight: 400,
          style: "normal",
        },
        {
          name: "Instrument Sans",
          data: instrumentSansBold,
          weight: 700,
          style: "normal",
        },
      ],
    },
  );
}
