// src/app/opengraph-image.tsx
//
// Open Graph image generated by Next.js' file-based convention.
// Output: GET /opengraph-image -> image/png, 1200x630.
//
// Colours come from src/lib/og-tokens.ts, the documented sRGB mirror of the
// .dark token block in globals.css. Dark theme deliberately: link previews
// mostly render in feeds where the dark card reads as the site's identity,
// and the dark accent #3B82F6 carries both the tile and the glow.

import { readFile } from "node:fs/promises";
import { join } from "node:path";

import { ImageResponse } from "next/og";

import {
  OG_GROUND,
  OG_TEXT,
  OG_TEXT_MUTED,
  OG_ACCENT,
  OG_ON_ACCENT,
  OG_ACCENT_RGB,
} from "@/lib/og-tokens";

export const alt = "Murat Zorlu: I build the internal tools companies run on";

export const size = {
  width: 1200,
  height: 630,
} as const;

export const contentType = "image/png";

// Satori does not support WOFF2 — it only parses TTF / OTF, which is why these
// are TTFs rather than the WOFF2 that next/font serves the browser.
//
// The files are vendored in src/app/_fonts/ and read off disk, NOT fetched.
// They were previously pulled from fonts.gstatic.com on every request, which
// forced this route (and twitter-image, which re-exports it) out of static
// generation: a route that awaits a network call cannot be prerendered. That
// put three third-party round trips on the critical path of every link-preview
// scrape, so a Google Fonts outage or latency spike broke social cards
// site-wide. Reading locally means the whole image is built once, at build.
//
// `_fonts` has a leading underscore, so the App Router treats it as a private
// folder and never routes it; the files are build-time inputs and are not
// served. process.cwd() is the project root during the build, which is the
// only time this runs.
//
// Same faces the site loads in layout.tsx: Darker Grotesque 800 is the
// display face (headings), Instrument Sans is the body face and the face
// the header's MZ tile and wordmark render in.
const FONT_DIR = join(process.cwd(), "src", "app", "_fonts");

export default async function OpengraphImage(): Promise<ImageResponse> {
  const [darkerGrotesque, instrumentSans, instrumentSansBold] =
    await Promise.all([
      readFile(join(FONT_DIR, "DarkerGrotesque-ExtraBold.ttf")),
      readFile(join(FONT_DIR, "InstrumentSans-Regular.ttf")),
      readFile(join(FONT_DIR, "InstrumentSans-Bold.ttf")),
    ]);

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          background: OG_GROUND,
          color: OG_TEXT,
          fontFamily: "Instrument Sans",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          padding: "72px 80px",
          position: "relative",
        }}
      >
        {/* Top-right radial glow in the accent, same device as the hero. */}
        <div
          style={{
            position: "absolute",
            top: 0,
            right: 0,
            width: "780px",
            height: "780px",
            display: "flex",
            backgroundImage: `radial-gradient(circle at 70% 25%, rgba(${OG_ACCENT_RGB}, 0.20) 0%, rgba(${OG_ACCENT_RGB}, 0.06) 35%, rgba(${OG_ACCENT_RGB}, 0) 70%)`,
          }}
        />

        {/* Header lockup: the MZ tile plus wordmark, dark-theme identity.
            Tile geometry scales the header's 28px rounded-md tile: 64px box,
            64 * (6/28) = 14px radius, 64 * (12/28) = 27px letters. */}
        <div
          style={{
            display: "flex",
            flexDirection: "row",
            alignItems: "center",
            gap: "22px",
            position: "relative",
          }}
        >
          <div
            style={{
              width: "64px",
              height: "64px",
              borderRadius: "14px",
              background: OG_ACCENT,
              color: OG_ON_ACCENT,
              fontSize: 27,
              fontWeight: 700,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            MZ
          </div>
          <div
            style={{
              fontSize: 34,
              fontWeight: 700,
              letterSpacing: "-0.01em",
              display: "flex",
            }}
          >
            Murat Zorlu
          </div>
        </div>

        {/* Headline in the display face. The break is forced: letting it
            wrap at this size strands "on" alone on a third line. */}
        <div
          style={{
            fontFamily: "Darker Grotesque",
            fontSize: 100,
            fontWeight: 800,
            lineHeight: 1.0,
            letterSpacing: "0.002em",
            color: OG_TEXT,
            display: "flex",
            flexDirection: "column",
            position: "relative",
          }}
        >
          <div style={{ display: "flex" }}>I build the internal tools</div>
          <div style={{ display: "flex" }}>companies run on</div>
        </div>

        {/* Bottom row: stack left, domain right. */}
        <div
          style={{
            display: "flex",
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            position: "relative",
          }}
        >
          <div
            style={{
              fontSize: 28,
              color: OG_TEXT_MUTED,
              letterSpacing: "0.02em",
              display: "flex",
            }}
          >
            Next.js · NestJS · Go · PostgreSQL
          </div>
          <div
            style={{
              fontSize: 24,
              color: OG_TEXT_MUTED,
              letterSpacing: "0.06em",
              display: "flex",
            }}
          >
            muratzorlu.dev
          </div>
        </div>
      </div>
    ),
    {
      ...size,
      fonts: [
        {
          name: "Darker Grotesque",
          data: darkerGrotesque,
          weight: 800,
          style: "normal",
        },
        {
          name: "Instrument Sans",
          data: instrumentSans,
          weight: 400,
          style: "normal",
        },
        {
          name: "Instrument Sans",
          data: instrumentSansBold,
          weight: 700,
          style: "normal",
        },
      ],
    },
  );
}
