// src/app/[locale]/opengraph-image.tsx
//
// Open Graph image generated by Next.js' file-based convention, one per
// locale. Output: GET /tr/opengraph-image and /en/opengraph-image -> image/png,
// 1200x630. Those URLs carry their locale segment, so src/proxy.ts leaves
// them alone rather than redirecting /tr/... to the bare path.
//
// Colours come from src/lib/og-tokens.ts, the documented sRGB mirror of the
// .dark token block in globals.css. Dark theme deliberately: link previews
// mostly render in feeds where the dark card reads as the site's identity,
// and the dark accent #3B82F6 carries both the tile and the glow.

import { readFile } from "node:fs/promises";
import { join } from "node:path";

import { ImageResponse } from "next/og";
import { hasLocale } from "next-intl";
import { getTranslations } from "next-intl/server";

import { routing } from "@/i18n/routing";
import {
  OG_GROUND,
  OG_TEXT,
  OG_TEXT_MUTED,
  OG_ACCENT,
  OG_ON_ACCENT,
  OG_ACCENT_RGB,
} from "@/lib/og-tokens";

// A static export, so it cannot follow the locale; the name is the one thing
// on the card that reads the same in both languages.
export const alt = "Murat Zorlu";

export const size = {
  width: 1200,
  height: 630,
} as const;

export const contentType = "image/png";

// Satori does not support WOFF2 — it only parses TTF / OTF, which is why these
// are TTFs rather than the WOFF2 that next/font serves the browser.
//
// The files are vendored in src/app/_fonts/ and read off disk, NOT fetched.
// Reading locally means the whole image is built once, at build.
//
// `_fonts` has a leading underscore, so the App Router treats it as a private
// folder and never routes it; the files are build-time inputs and are not
// served. process.cwd() is the project root during the build, which is the
// only time this runs.
//
// Same faces the site loads in layout.tsx: Darker Grotesque 800 is the
// display face (headings), Instrument Sans is the body face and the face
// the header's MZ tile and wordmark render in.
const FONT_DIR = join(process.cwd(), "src", "app", "_fonts");

type Props = {
  params: Promise<{ locale: string }>;
};

/**
 * Both images are rendered at build. Without this the route sits under a
 * dynamic segment and Next renders it on demand, which is what the move to
 * on-disk fonts was meant to end.
 */
export function generateStaticParams(): Array<{ locale: string }> {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function OpengraphImage({ params }: Props): Promise<ImageResponse> {
  const { locale: requested } = await params;
  const locale = hasLocale(routing.locales, requested) ? requested : routing.defaultLocale;
  const t = await getTranslations({ locale, namespace: "ogImage" });

  const [darkerGrotesque, instrumentSans, instrumentSansBold] =
    await Promise.all([
      readFile(join(FONT_DIR, "DarkerGrotesque-ExtraBold.ttf")),
      readFile(join(FONT_DIR, "InstrumentSans-Regular.ttf")),
      readFile(join(FONT_DIR, "InstrumentSans-Bold.ttf")),
    ]);

  // The Turkish second line is long, so the headline steps down one size to
  // keep two lines at 100px from running into the right edge.
  const headlineSize = locale === "tr" ? 88 : 100;

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          background: OG_GROUND,
          color: OG_TEXT,
          fontFamily: "Instrument Sans",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          padding: "72px 80px",
          position: "relative",
        }}
      >
        {/* Top-right radial glow in the accent, same device as the hero. */}
        <div
          style={{
            position: "absolute",
            top: 0,
            right: 0,
            width: "780px",
            height: "780px",
            display: "flex",
            backgroundImage: `radial-gradient(circle at 70% 25%, rgba(${OG_ACCENT_RGB}, 0.20) 0%, rgba(${OG_ACCENT_RGB}, 0.06) 35%, rgba(${OG_ACCENT_RGB}, 0) 70%)`,
          }}
        />

        {/* Header lockup: the MZ tile plus wordmark, dark-theme identity.
            Tile geometry scales the header's 28px rounded-md tile: 64px box,
            64 * (6/28) = 14px radius, 64 * (12/28) = 27px letters. */}
        <div
          style={{
            display: "flex",
            flexDirection: "row",
            alignItems: "center",
            gap: "22px",
            position: "relative",
          }}
        >
          <div
            style={{
              width: "64px",
              height: "64px",
              borderRadius: "14px",
              background: OG_ACCENT,
              color: OG_ON_ACCENT,
              fontSize: 27,
              fontWeight: 700,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            MZ
          </div>
          <div
            style={{
              fontSize: 34,
              fontWeight: 700,
              letterSpacing: "-0.01em",
              display: "flex",
            }}
          >
            Murat Zorlu
          </div>
        </div>

        {/* Headline in the display face. The break is forced: letting it
            wrap at this size strands a word alone on a third line. */}
        <div
          style={{
            fontFamily: "Darker Grotesque",
            fontSize: headlineSize,
            fontWeight: 800,
            lineHeight: 1.0,
            letterSpacing: "0.002em",
            color: OG_TEXT,
            display: "flex",
            flexDirection: "column",
            position: "relative",
          }}
        >
          <div style={{ display: "flex" }}>{t("line1")}</div>
          <div style={{ display: "flex" }}>{t("line2")}</div>
        </div>

        {/* Bottom row: stack (or sectors) left, domain right. */}
        <div
          style={{
            display: "flex",
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            position: "relative",
          }}
        >
          <div
            style={{
              fontSize: 28,
              color: OG_TEXT_MUTED,
              letterSpacing: "0.02em",
              display: "flex",
            }}
          >
            {t("footer")}
          </div>
          <div
            style={{
              fontSize: 24,
              color: OG_TEXT_MUTED,
              letterSpacing: "0.06em",
              display: "flex",
            }}
          >
            muratzorlu.dev
          </div>
        </div>
      </div>
    ),
    {
      ...size,
      fonts: [
        {
          name: "Darker Grotesque",
          data: darkerGrotesque,
          weight: 800,
          style: "normal",
        },
        {
          name: "Instrument Sans",
          data: instrumentSans,
          weight: 400,
          style: "normal",
        },
        {
          name: "Instrument Sans",
          data: instrumentSansBold,
          weight: 700,
          style: "normal",
        },
      ],
    },
  );
}
